version:  "2"
services:
  node:
    image:  "node:9"
    working_dir:  /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - '43712:43712'
    command:  "npm start"